---
title: "RI Calculation Result"
output: html_document
---

```{r setup, include=FALSE}
library(stringr)
library(knitr)
knitr::opts_chunk$set(echo = TRUE, results="hide")

```

## Parameters

```{r echo=F, results='asis'}
env <- Sys.getenv()

#library(knitr)
list <- as.list(env[grep("^AZURERI_", names(env))])
# replace sensitive values
list$AZURERI_BEARER <- paste0(substring(list$AZURERI_BEARER, 1, 10), '.. ..', substring(list$AZURERI_BEARER, first=nchar(list$AZURERI_BEARER)-10))

if (!is.null(list[["AZURERI_SASTOKEN"]])) {
  list$AZURERI_SASTOKEN <- paste0(substring(list$AZURERI_BEARER, 1, 10), '.. ..', substring(list$AZURERI_BEARER, first=nchar(list$AZURERI_BEARER)-10))
}

list$AZURERI_CONNECTIONSTRING <- 
  str_replace(
    str_replace(list$AZURERI_CONNECTIONSTRING, "Uid=([^;]){1}([^;]*){0,1};", "Uid=\\1*******;"),
    "Pwd=([^;]){1}([^;]*){0,1};", "Pwd=********;")

for (name in names(list)) {
    cat("- **", name, '** :', paste(' *', list[[name]], '* \n', sep = ""), sep = "")
}

billingPeriod <- Sys.getenv("AZURERI_BILLINGPERIOD")

if (is.null(billingPeriod)) {
  billingPeriod <- format(as.Date(format(Sys.Date(), "%Y-%m-01")) - 1, "%Y%m")
}

```

## Code load
```{r echo=T, results="hide", message=FALSE}
source("azureRI.R")

```
## Data load
```{r echo=T, results='markup'}

priceSheet <- azureRI.get("PriceList", azureRI.default, row.names = "BusinessKey", billingPeriod = billingPeriod) 
friendlyServiceNames <- azureRI.get("FriendlyServiceNames", azureRI.default, row.names = "BusinessKey", billingPeriod = billingPeriod )
instanceSizeFlexibility <- azureRI.get("InstanceSizeFlexibility", azureRI.default, row.names = "BusinessKey", billingPeriod = billingPeriod)


billingData <- azureRI.get(what="BillingData", apiObj = azureRI.default, row.names = "BusinessKey", billingPeriod = billingPeriod, reload=T)
riHoursUtilization <- azureRI.get(what="RIHoursUtilization", apiObj = azureRI.default, row.names = "BusinessKey", billingPeriod = billingPeriod, reload=T)
riHoursWithRICosts <- azureRI.get("RIHoursWithRICosts", billingPeriod = billingPeriod, reload=T) 
#billingData
#riHoursUtilization
```
## Basic RI Cost checks
```{r echo=T, results='asis'}
bdSum <- billingData %>% 
  group_by(SubscriptionName) %>% 
  summarize(
    RIHours = sum(RIHoursUsed, na.rm = T),
    RICost = sum(CostUsageFromRI, na.rm = T),
  )

riHoursSum <- riHoursUtilization %>% 
  group_by(SubscriptionName) %>% 
  summarize(
    RIHours = sum(RIHours, na.rm = T),
    RICost = sum(RICost, na.rm = T),
  )

#Diff
diff <- bdSum %>% full_join(y = riHoursSum, 
   by=c("SubscriptionName"="SubscriptionName")) %>%
   mutate(
     HoursDiff = RIHours.x - RIHours.y,
     CostsDiff = RICost.x - RICost.y
   )

kable(diff)
```


### Detailed differences

```{r echo=TRUE, results='asis'}
# Summarize and include instance ID
bdSum2 <- billingData %>% 
  filter(MeterCategory == "Virtual Machines") %>%
  mutate(InstanceIdShort = basename(InstanceId)) %>%
  group_by(SubscriptionName, InstanceIdShort, VMName, Date) %>% 
  summarize(
    RIHours = sum(RIHoursUsed, na.rm = T),
    RICost = sum(CostUsageFromRI, na.rm = T),
  )

riHoursSum2 <- riHoursWithRICosts %>%
  mutate(InstanceIdShort = basename(InstanceId)) %>%
  group_by(SubscriptionName, InstanceIdShort, VMName, Date) %>% 
  summarize(
    RIHours = sum(RIHours, na.rm = T),
    RICost = sum(RICost, na.rm = T),
  )


#Diff2
diff2 <- bdSum2 %>% full_join(y = riHoursSum2, 
                            by=c("SubscriptionName"="SubscriptionName", 
                                 "InstanceIdShort"="InstanceIdShort",
                                 "VMName"="VMName",
                                 "Date"="Date"
                                 )) %>%
  mutate(
    HoursDiff = RIHours.x - RIHours.y,
    CostsDiff = RICost.x - RICost.y
  ) %>%
  filter(
    HoursDiff != 0 | CostsDiff != 0
  )
kable(diff2)
```

## Storing updated data to database


```{r echo=T}

#priceSheet <- azureRI.get("PriceList", azureRI.default, row.names = "BusinessKey", reload=T) 
#friendlyServiceNames <- azureRI.get("FriendlyServiceNames", azureRI.default, row.names = "BusinessKey", reload=T)
#instanceSizeFlexibility <- azureRI.get("InstanceSizeFlexibility", azureRI.default, row.names = "BusinessKey", reload=T)


#billingData <- azureRI.get(what="BillingData", apiObj = azureRI.default, row.names = "BusinessKey", reload=T)
#riHoursUtilization <- azureRI.get(what="RIHoursUtilization", apiObj = azureRI.default, row.names = "BusinessKey", reload=T)  

azureRI.set(what="PriceList", apiObj = azureRI.default, data = priceSheet, billingPeriod = billingPeriod)
azureRI.set(what="FriendlyServiceNames", apiObj = azureRI.default, data = friendlyServiceNames, billingPeriod = billingPeriod)
azureRI.set(what="InstanceSizeFlexibility", apiObj = azureRI.default, data = instanceSizeFlexibility, billingPeriod = billingPeriod)
azureRI.set(what="BillingData", apiObj = azureRI.default, data = billingData, billingPeriod = billingPeriod)
azureRI.set(what="RIHoursUtilization", apiObj = azureRI.default, data = riHoursUtilization, billingPeriod = billingPeriod)

```